package models

type filtroConvenio struct {
	Emp_Data                                string  `json:"empenho_data"`
	Emp_Numero                              string  `json:"empenho_numero"`
	Credor                                  string  `json:"credor"`
	Valor_Empenhado                         float64 `json:"valor_empenhado"`
	Valor_Liquidado                         float64 `json:"valor_liquidado"`
	Valor_Pago                              float64 `json:"valor_pago"`
	Valor_PagoRetencao                      float64 `json:"valor_pago_mais_retencao"`
	Anulado_Empenho                         float64 `json:"valor_anulado"`
	Qtde_Notas_Fiscais                      string  `json:"qtde_notas_fiscais"`
	Qtde_NFe                                string  `json:"qtde_nfe"`
	Contratos                               string  `json:"contratos"`
	Ent_codigo                              string  `json:"ent_codigo"`
	Qtde_beneficiarios                      int     `json:"qtde_beneficiarios"`
	Instrumento_contrato                    string  `json:"instrumento_contrato"`
	Fonte_recurso_fonte                     *string `json:"fonte_recurso_fonte"`
	Tipo_concurso                           *string `json:"tipo_concurso"`
	Num_Concurso                            *string `json:"num_concurso"`
	Assistencia_social                      *string `json:"assistencia_social"`
	Diarias                                 *int    `json:"diarias"`
	Relevante                               *string `json:"relevante"`
	Unidade_gestora                         *string `json:"unidade_gestora"`
	Municipio                               *string `json:"municipio"`
	Exercicio                               *string `json:"exercicio"`
	Codigo_ug                               *string `json:"codigo_ug"`
	Projeto_atividade                       *string `json:"projeto_atividade"`
	Dotacao                                 *string `json:"dotacao"`
	Num_obra                                *string `json:"num_obra"`
	Tipo_serv_engenharia                    *string `json:"tipo_serv_engenharia"`
	Destinacao_recurso_grupo                *string `json:"destinacao_recurso_grupo"`
	Destinacao_recurso_iduso                *string `json:"destinacao_recurso_iduso"`
	Destinacao_recurso_codiog_iduso         *string `json:"destinacao_recurso_codiog_iduso"`
	Codigo_destinacao_recurso               *string `json:"codigo_destinacao_recurso"`
	Codigo_destinacao_recurso_especificacao *string `json:"codigo_destinacao_recurso_especificacao"`
	Destinacao_recurso_codigo_grupo         *string `json:"destinacao_recurso_codigo_grupo"`
	Fund_compra_direta_codigo               *string `json:"fund_compra_direta_codigo"`
	Fund_compra_direta_descricao            *string `json:"fund_compra_direta_descricao"`
	Destinacao_recurso                      *string `json:"destinacao_recurso"`
	Orgao                                   *string `json:"orgao"`
	UnidadeOrcamentaria                     *string `json:"unidade_orcamentaria"`
	Unidade_orcamentaria_codigo             *string `json:"unidade_orcamentaria_codigo"`
	Funcao_codigo                           *string `json:"funcao_codigo"`
	Funcao_descricao                        *string `json:"funcao_descricao"`
	Subfuncao_codigo                        *string `json:"subfuncao_codigo"`
	Subfuncao_descricao                     *string `json:"subfuncao_descricao"`
	Programa_codigo                         *string `json:"programa_codigo"`
	Num_Projeto_Atividade                   *string `json:"num_projeto_atividade"`
	Categoria_Economica                     *string `json:"categoria_economica"`
	Natureza_Despesa                        *string `json:"natureza_despesa"`
	Modalidade_aplicacao_codigo             *string `json:"modalidade_aplicacao_codigo"`
	Elemento_despesa_codigo                 *string `json:"elemento_despesa_codigo"`
	Elemento_despesa_descricao              *string `json:"elemento_despesa_descricao"`
	Subelemento_despesa_codigo              *string `json:"subelemento_despesa_codigo"`
	Subelemento_despesa                     *string `json:"subelemento_despesa"`
	Descricao                               *string `json:"descricao"`
	Num_processo_licitatorio                *string `json:"num_processo_licitatorio"`
	Tipo_Contrato                           *string `json:"tipo_contrato"`
	Num_aditivo_contrato                    *string `json:"num_aditivo_contrato"`
	Num_convenio                            *string `json:"num_convenio"`
	Num_aditivo_convenio                    *string `json:"num_aditivo_convenio"`
	Compra_direta                           *string `json:"compra_direta"`
	Tipo                                    *string `json:"tipo"`
	Mes_referencia                          *string `json:"mes_referencia"`
	Identificacao_credor                    *string `json:"identificacao_credor"`
	Tipo_pesssoaCodigo                      *string `json:"tipo_pesssoa_codigo"`
}
